homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.7119
  longitude: 5.4437
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  # Customization file
  customize: !include customize.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.25:3218


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: domo.julieetguillaume.fr

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: linky
    username: !secret linky_username
    password: !secret linky_password
    monitored_variables:
      - daily_1d_consumption
      - daily_2d_consumption
      - monthly_current_consumption
      - monthly_1m_consumption
      - yearly_current_consumption
      - yearly_2y_consumption
#### To calculate Peak and Off-Peak consumption ####
      - halfhourly_00_00_consumption
      - halfhourly_00_30_consumption
      - halfhourly_01_00_consumption
      - halfhourly_01_30_consumption
      - halfhourly_02_00_consumption
      - halfhourly_02_30_consumption
      - halfhourly_03_00_consumption
      - halfhourly_03_30_consumption
      - halfhourly_04_00_consumption
      - halfhourly_04_30_consumption
      - halfhourly_05_00_consumption
      - halfhourly_05_30_consumption
      - halfhourly_06_00_consumption
      - halfhourly_06_30_consumption
      - halfhourly_07_00_consumption
      - halfhourly_07_30_consumption
      - halfhourly_08_00_consumption
      - halfhourly_08_30_consumption
      - halfhourly_09_00_consumption
      - halfhourly_09_30_consumption
      - halfhourly_10_00_consumption
      - halfhourly_10_30_consumption
      - halfhourly_11_00_consumption
      - halfhourly_11_30_consumption
      - halfhourly_12_00_consumption
      - halfhourly_12_30_consumption
      - halfhourly_13_00_consumption
      - halfhourly_13_30_consumption
      - halfhourly_14_00_consumption
      - halfhourly_14_30_consumption
      - halfhourly_15_00_consumption
      - halfhourly_15_30_consumption
      - halfhourly_16_00_consumption
      - halfhourly_16_30_consumption
      - halfhourly_17_00_consumption
      - halfhourly_17_30_consumption
      - halfhourly_18_00_consumption
      - halfhourly_18_30_consumption
      - halfhourly_19_00_consumption
      - halfhourly_19_30_consumption
      - halfhourly_20_00_consumption
      - halfhourly_20_30_consumption
      - halfhourly_21_00_consumption
      - halfhourly_21_30_consumption
      - halfhourly_22_00_consumption
      - halfhourly_22_30_consumption
      - halfhourly_23_00_consumption
      - halfhourly_23_30_consumption
######################## Conso Templates ####################################""
  - platform : template
    sensors:
      heures_creuses:
        friendly_name: 'Heures creuses'
        value_template: >
          {{(((states('sensor.linky_halfhourly_23_00_consumption')|float) +(states('sensor.linky_halfhourly_23_30_consumption') |float)+ (states('sensor.linky_halfhourly_00_00_consumption')|float) + (states('sensor.linky_halfhourly_00_30_consumption') |float)+ (states('sensor.linky_halfhourly_01_00_consumption')|float) +(states('sensor.linky_halfhourly_01_30_consumption') |float)+ (states('sensor.linky_halfhourly_02_00_consumption')|float) +(states('sensor.linky_halfhourly_02_30_consumption') |float)+ (states('sensor.linky_halfhourly_03_00_consumption')|float) +(states('sensor.linky_halfhourly_03_30_consumption') |float) +(states('sensor.linky_halfhourly_04_00_consumption') |float)+ (states('sensor.linky_halfhourly_04_30_consumption')|float) + (states('sensor.linky_halfhourly_05_00_consumption') |float)+ (states('sensor.linky_halfhourly_05_30_consumption')|float) +(states('sensor.linky_halfhourly_06_00_consumption') |float)+ (states('sensor.linky_halfhourly_06_30_consumption')|float)  ) /2)| round(3)  }}
        unit_of_measurement: 'kWh'
  - platform : template
    sensors:
      price_heures_creuses:
        friendly_name: 'Prix Heures creuses'
        value_template: >
          {{ (states.sensor.heures_creuses.state | multiply(0.1252))  | round(2)}}
        unit_of_measurement: '€'
  - platform : template
    sensors:
      heures_pleines:
        friendly_name: 'Heures pleines'
        value_template: >
          {{((states('sensor.linky_daily_1d_consumption')|float)- (states.sensor.heures_creuses.state)|float) | round (3) }}
        unit_of_measurement: 'kWh'
  - platform : template
    sensors:
      price_heures_pleines:
        friendly_name: 'Prix Heures pleines'
        value_template: >
          {{ (states.sensor.heures_pleines.state | multiply(0.1593)) | round(2)}}
        unit_of_measurement: '€'
  - platform : template
    sensors:
      price_conso_total:
        friendly_name: 'Prix Total'
        value_template: >
          {{ ( (states('sensor.price_heures_creuses')|float) + (states('sensor.price_heures_pleines')|float) )|round(2) }}
        unit_of_measurement: '€'


  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: synologydsm
    host: 192.168.1.51
    username: admin
    password: ross20
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - volume_percentage_used
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Netatmo
netatmo:
  api_key: !secret netatmo_apikey
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

climate:
  - platform: netatmo
  
camera:
  - platform: netatmo
  
rfxtrx:
  device: /dev/ttyUSB1

zwave:
  usb_path: /dev/ttyUSB0
  
switch:
  platform: rfxtrx
  automatic_add: True
  devices:
    0b1100000136961601010f70:
      name: "lumière canapé"
    0b1100010136961603010f70:
      name: "lumière salle à manger"
    0b1100040136961602010f70:
      name: "lumière tv"

cover:
  - platform: rfxtrx
    automatic_add: True
    signal_repetitions: 2
    devices:
      071a000001020101: # RFY Portail exterieur
        name: "Portail extérieur"
      071a000006010101: # RFY volet chambre Eloise
        name: "Volet Éloïse"
      071a000006010201: # RFY volet chambre Clement
        name: "Volet Clément"      
      071a000006010301: # RFY volet chambre Bureau
        name: "Volet Bureau"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
